# Generated by Django 4.1 on 2022-08-14 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('sancion_a_aplicar', models.TextField(blank=True)),
                ('motivo_de_sancion', models.TextField(blank=True)),
                ('fecha_del_incidente', models.DateField(default=datetime.date.today)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
