# Generated by Django 4.1 on 2022-08-16 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0002_sancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('hijos_menores', models.IntegerField(default=0)),
                ('hijos_mayores_discapacitados', models.IntegerField(default=0)),
                ('total_hijos_para_bonificacion', models.IntegerField(default=0)),
                ('fecha_a_pagar', models.DateField(default=datetime.date.today)),
                ('salario_minimo_mensual_vigente', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('bonificacion_familiar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
