# Generated by Django 4.1 on 2022-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0003_bonificacionfamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_firma_trabajador', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
