# Generated by Django 4.1 on 2022-08-17 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0004_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='permiso',
            name='cedula',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='permiso',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_inicio_ausencia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_reincorporacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='permiso',
            name='foto_firma_encargado_rrhh',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='motivo_ausencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='permiso',
            name='recibira_descuento',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='permiso',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='foto_firma_trabajador',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
