# Generated by Django 4.1 on 2022-08-17 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0005_permiso_apellidos_permiso_cedula_permiso_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDeCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_cargo', models.CharField(max_length=100)),
                ('experiencia_requerida', models.TextField()),
                ('conocimientos_requeridos', models.TextField()),
                ('nivel_de_estudios', models.TextField()),
                ('rango_salarial', models.TextField()),
                ('requiere_tener_auto_propio', models.CharField(max_length=2)),
                ('otros_requisitos', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
