# Generated by Django 4.1 on 2022-08-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0006_perfildecargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificacionDePermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('fecha_inicio_ausencia', models.DateField(default=datetime.date.today)),
                ('fecha_reincorporacion', models.DateField(default=datetime.date.today)),
                ('archivo_con_justificacion', models.FileField(upload_to='documentos/')),
                ('existe_discrepancia_permiso_y_justificacion', models.CharField(max_length=2)),
                ('foto_firma_encargado_rrhh', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
