# Generated by Django 4.1 on 2022-08-18 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0007_justificaciondepermiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('fecha_aplicar_descuento', models.DateField(default=datetime.date.today)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_con_ingresos_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('descuento_cuota_IPS', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('descuento_sanciones', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('descuento_inasistencias', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('otros_descuentos', models.TextField(blank=True)),
                ('descuentos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
