# Generated by Django 4.1 on 2022-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0008_descuentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentos',
            old_name='descuento_cuota_IPS',
            new_name='descuento_cuota_ips',
        ),
    ]
