# Generated by Django 4.1 on 2022-08-18 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0009_rename_descuento_cuota_ips_descuentos_descuento_cuota_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('fecha_aplicar_ingresos_extras', models.DateField(default=datetime.date.today)),
                ('ingresos_por_horas_extras', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('bonificacion_familiar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('aguinaldos', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('otros_ingresos_extras', models.TextField(blank=True)),
                ('ingresos_extras_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
