# Generated by Django 4.1 on 2022-08-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0010_ingresosextras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngresosExtras',
            new_name='IngresoExtra',
        ),
    ]
