# Generated by Django 4.1 on 2022-08-19 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0011_rename_ingresosextras_ingresoextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('cantidad_inicial_dias_vacaciones', models.IntegerField(default=0)),
                ('dias_que_se_tomara_vacaciones', models.IntegerField(default=0)),
                ('dias_restantes_vacaciones', models.IntegerField(default=0)),
                ('fecha_inicio_vacaciones', models.DateField(default=datetime.date.today)),
                ('fecha_fin_vacaciones', models.DateField(default=datetime.date.today)),
                ('foto_firma_trabajador', models.ImageField(upload_to='images/')),
                ('foto_firma_encargado_rrhh', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
