# Generated by Django 4.1 on 2022-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0013_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aguinaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('salario_enero', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_febrero', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_marzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_abril', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_mayo', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_junio', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_julio', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_agosto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_septiembre', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_octubre', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_noviembre', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_diciembre', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('aguinaldos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
