# Generated by Django 4.1 on 2022-08-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0015_aguinaldo_anno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_abril',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_agosto',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_diciembre',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_enero',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_febrero',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_julio',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_junio',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_marzo',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_mayo',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_noviembre',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_octubre',
        ),
        migrations.RemoveField(
            model_name='aguinaldo',
            name='salario_septiembre',
        ),
    ]
