# Generated by Django 4.1 on 2022-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0016_remove_aguinaldo_salario_abril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_abril',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_agosto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_diciembre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_enero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_febrero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_julio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_junio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_marzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_mayo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_noviembre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_octubre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='aguinaldo',
            name='salario_septiembre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
