# Generated by Django 4.1 on 2022-08-20 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0017_aguinaldo_salario_abril_aguinaldo_salario_agosto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencias', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
