# Generated by Django 4.1 on 2022-08-20 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0018_fechaasistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('fecha_asistencia', models.DateField(default=datetime.date.today)),
                ('hora_llegada', models.TimeField(blank=True)),
                ('hora_salida', models.TimeField(blank=True)),
                ('vino_a_trabajar', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
