# Generated by Django 4.1 on 2022-08-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0019_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_de_trabajadores', to='app_rrhh.fechaasistencia'),
        ),
    ]
