# Generated by Django 4.1 on 2022-08-21 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0020_alter_asistencia_fecha_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionDelPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('nombre_del_cargo', models.CharField(max_length=100)),
                ('fecha_inicio_contrato', models.DateField(default=datetime.date.today)),
                ('fecha_fin_contrato', models.DateField(default=datetime.date.today)),
                ('motivo_de_finalizacion_contrato', models.TextField()),
                ('tipo_de_salario', models.CharField(max_length=200)),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('vacaciones_no_disfrutadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('aguinaldos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_por_horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('descuentos_en_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_total_a_liquidar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('foto_firma_encargado_rrhh', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
