# Generated by Django 4.1 on 2022-08-21 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0021_liquidaciondelpersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionDeSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('ingresos_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('salario_total_a_liquidar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('fecha_de_pago', models.DateField(default=datetime.date.today)),
                ('foto_firma_encargado_rrhh', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
