# Generated by Django 4.1 on 2022-08-21 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0022_liquidaciondesalario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fecha_de_vencimiento_cedula', models.DateField(blank=True, default=datetime.date.today)),
                ('curriculum', models.FileField(blank=True, upload_to='curriculums/')),
                ('nivel_maximo_de_educacion_obtenido', models.CharField(max_length=100)),
                ('tiene_antecedentes_penales', models.CharField(max_length=2)),
                ('numero_ips', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=100)),
                ('evaluacion_de_desempeno', models.FileField(upload_to='documentos/')),
                ('sanciones', models.TextField(blank=True)),
                ('permisos_para_ausentarse', models.TextField(blank=True)),
                ('otros_datos', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
