# Generated by Django 4.1 on 2022-08-22 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0023_legajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('nivel_maximo_de_educacion_obtenido', models.CharField(max_length=100)),
                ('numero_ips', models.CharField(max_length=30)),
                ('numero_cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('tiempo_completo_o_parcial', models.CharField(max_length=20)),
                ('firma_trabajador', models.ImageField(upload_to='images/')),
                ('firma_encargado_rrhh', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
