# Generated by Django 4.1 on 2022-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0024_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='clausulas_del_contrato',
            field=models.FileField(default='', upload_to='documentos/'),
        ),
    ]
