# Generated by Django 4.1 on 2022-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0025_contrato_clausulas_del_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(default=0)),
                ('evaluacion_de_desempeno_personal', models.FileField(upload_to='documentos/')),
                ('trabajadores_contratados', models.IntegerField(default=0)),
                ('trabajadores_que_salieron', models.IntegerField(default=0)),
                ('edad_promedio_personal', models.IntegerField(default=0)),
                ('tasa_absentismo', models.CharField(max_length=20)),
                ('salario_promedio_personal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('dias_para_ocupar_cargo_vacante', models.IntegerField(default=0)),
                ('annos_de_trabajador_con_mas_tiempo_en_empresa', models.IntegerField(default=0)),
                ('numero_cursos_ofrecidos_trabajadores', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
