# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0026_informeweb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeweb',
            old_name='dias_para_ocupar_cargo_vacante',
            new_name='promedio_dias_para_ocupar_cargo_vacante',
        ),
    ]
