# Generated by Django 4.1 on 2022-08-23 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0027_rename_dias_para_ocupar_cargo_vacante_informeweb_promedio_dias_para_ocupar_cargo_vacante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaEmpleadosMinisterioDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patronal', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('domicilio', models.CharField(max_length=100)),
                ('cantidad_hijos_menores', models.IntegerField(default=0)),
                ('fecha_nacimiento_del_menor', models.DateField(blank=True, default=datetime.date.today)),
                ('estado_civil', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('horario_de_trabajo', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('fecha_inicio_trabajo_del_menor', models.DateField(blank=True, default=datetime.date.today)),
                ('situacion_escolar_menor', models.CharField(max_length=20)),
                ('fecha_entrada', models.DateField(default=datetime.date.today)),
                ('fecha_salida', models.DateField(blank=True, default=datetime.date.today)),
                ('motivo_de_salida', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
