# Generated by Django 4.1 on 2022-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0028_planillaempleadosministeriodetrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaSueldosMinisterioDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patronal', models.IntegerField(default=0)),
                ('cedula', models.CharField(max_length=15)),
                ('forma_de_pago', models.CharField(max_length=1)),
                ('importe_unitario', models.IntegerField(default=0)),
                ('horas_trabajadas_enero', models.IntegerField(default=0)),
                ('salario_percibido_enero', models.IntegerField(default=0)),
                ('horas_trabajadas_febrero', models.IntegerField(default=0)),
                ('salario_percibido_febrero', models.IntegerField(default=0)),
                ('horas_trabajadas_marzo', models.IntegerField(default=0)),
                ('salario_percibido_marzo', models.IntegerField(default=0)),
                ('horas_trabajadas_abril', models.IntegerField(default=0)),
                ('salario_percibido_abril', models.IntegerField(default=0)),
                ('horas_trabajadas_mayo', models.IntegerField(default=0)),
                ('salario_percibido_mayo', models.IntegerField(default=0)),
                ('horas_trabajadas_junio', models.IntegerField(default=0)),
                ('salario_percibido_junio', models.IntegerField(default=0)),
                ('horas_trabajadas_julio', models.IntegerField(default=0)),
                ('salario_percibido_julio', models.IntegerField(default=0)),
                ('horas_trabajadas_agosto', models.IntegerField(default=0)),
                ('salario_percibido_agosto', models.IntegerField(default=0)),
                ('horas_trabajadas_septiembre', models.IntegerField(default=0)),
                ('salario_percibido_septiembre', models.IntegerField(default=0)),
                ('horas_trabajadas_octubre', models.IntegerField(default=0)),
                ('salario_percibido_octubre', models.IntegerField(default=0)),
                ('horas_trabajadas_noviembre', models.IntegerField(default=0)),
                ('salario_percibido_noviembre', models.IntegerField(default=0)),
                ('horas_trabajadas_diciembre', models.IntegerField(default=0)),
                ('salario_percibido_diciembre', models.IntegerField(default=0)),
                ('horas_extras_50_por_ciento_durante_anno', models.IntegerField(default=0)),
                ('salario_percibido_horas_extras_50_por_ciento_anno', models.IntegerField(default=0)),
                ('horas_extras_100_por_ciento_durante_anno', models.IntegerField(default=0)),
                ('salario_percibido_horas_extras_100_por_ciento_anno', models.IntegerField(default=0)),
                ('aguinaldo', models.IntegerField(default=0)),
                ('beneficios', models.IntegerField(default=0)),
                ('bonificaciones', models.IntegerField(default=0)),
                ('vacaciones', models.IntegerField(default=0)),
                ('horas_trabajadas_incluyendo_horas_extras', models.IntegerField(default=0)),
                ('total_recibido_en_concepto_de_salario', models.IntegerField(default=0)),
                ('total_incluyendo_ingresos_extras', models.IntegerField(default=0)),
            ],
        ),
    ]
