# Generated by Django 4.1 on 2022-08-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0030_planillaresumengeneralministeriodetrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaempleadosministeriodetrabajo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='planillaresumengeneralministeriodetrabajo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='planillasueldosministeriodetrabajo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
