# Generated by Django 4.1 on 2022-08-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0031_planillaempleadosministeriodetrabajo_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillaempleadosministeriodetrabajo',
            name='estado',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
