# Generated by Django 4.1 on 2022-08-24 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0032_alter_planillaempleadosministeriodetrabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaIPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_orden', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numero_de_asegurado', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=15)),
                ('salario_imponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('categoria', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(default=0)),
                ('dias_trabajados_mes_anterior', models.IntegerField(default=0)),
                ('dias_trabajados_mes_actual', models.IntegerField(default=0)),
                ('reconocimiento_servicios_anteriores', models.TextField(blank=True)),
                ('firma_encargado_rrhh', models.ImageField(default='', upload_to='images/')),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
